# Generated by Django 2.1.3 on 2018-11-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
